// Generated by gencpp from file forklift/cameraInfo.msg
// DO NOT EDIT!


#ifndef FORKLIFT_MESSAGE_CAMERAINFO_H
#define FORKLIFT_MESSAGE_CAMERAINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace forklift
{
template <class ContainerAllocator>
struct cameraInfo_
{
  typedef cameraInfo_<ContainerAllocator> Type;

  cameraInfo_()
    : connected(0)
    , distance(0.0)
    , offsetRight(0.0)
    , offsetLeft(0.0)  {
    }
  cameraInfo_(const ContainerAllocator& _alloc)
    : connected(0)
    , distance(0.0)
    , offsetRight(0.0)
    , offsetLeft(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _connected_type;
  _connected_type connected;

   typedef float _distance_type;
  _distance_type distance;

   typedef float _offsetRight_type;
  _offsetRight_type offsetRight;

   typedef float _offsetLeft_type;
  _offsetLeft_type offsetLeft;




  typedef boost::shared_ptr< ::forklift::cameraInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::forklift::cameraInfo_<ContainerAllocator> const> ConstPtr;

}; // struct cameraInfo_

typedef ::forklift::cameraInfo_<std::allocator<void> > cameraInfo;

typedef boost::shared_ptr< ::forklift::cameraInfo > cameraInfoPtr;
typedef boost::shared_ptr< ::forklift::cameraInfo const> cameraInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::forklift::cameraInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::forklift::cameraInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace forklift

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'forklift': ['/home/curtis_interns/catkin_ws/src/forklift/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::forklift::cameraInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::forklift::cameraInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::forklift::cameraInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::forklift::cameraInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::forklift::cameraInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::forklift::cameraInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::forklift::cameraInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a27296fffd6a071bb8b6b8263bdeaebb";
  }

  static const char* value(const ::forklift::cameraInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa27296fffd6a071bULL;
  static const uint64_t static_value2 = 0xb8b6b8263bdeaebbULL;
};

template<class ContainerAllocator>
struct DataType< ::forklift::cameraInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "forklift/cameraInfo";
  }

  static const char* value(const ::forklift::cameraInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::forklift::cameraInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 connected\n\
float32 distance\n\
float32 offsetRight\n\
float32 offsetLeft\n\
";
  }

  static const char* value(const ::forklift::cameraInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::forklift::cameraInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.connected);
      stream.next(m.distance);
      stream.next(m.offsetRight);
      stream.next(m.offsetLeft);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cameraInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::forklift::cameraInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::forklift::cameraInfo_<ContainerAllocator>& v)
  {
    s << indent << "connected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.connected);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    s << indent << "offsetRight: ";
    Printer<float>::stream(s, indent + "  ", v.offsetRight);
    s << indent << "offsetLeft: ";
    Printer<float>::stream(s, indent + "  ", v.offsetLeft);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FORKLIFT_MESSAGE_CAMERAINFO_H
